name = "Markie Craft"
author = "Binary Fission"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e155521076341df459e0c263bade6387a23092572e35a7dcf155d3cc0177443c"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
