name = "Markie Craft"
author = "BinaryFission"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1b7042e33d8f0e9d67d4e2360419ccc4cfd44227c7a45609ffb2dbd4669b7ea"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
